server:
  port: 8087

spring:
  config:
    import: "classpath:common.yml"
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: Thai@11052004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

data:
  redis:
    host: redis
    port: 6379
    password: Thai@11052004
    timeout: 60000

cache:
  type: redis



