application-name: payment-service

server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: PLAINTEXT
    consumer:
      client-id: laundry-payment-service
      group-id: duis-detector
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
      #Khi thêm 1 consumer thay vì reblance để quản lý partitions thì chia từ mỗi consumer sang
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
      max-poll-records: 500
      max-poll-interval-ms: 15000
      session-timeout-ms: 5000
      heartbeat-interval-ms: 5000
      enable-auto-commit: false
      fetch-min-bytes: 5000
      fetch-max-wait-ms: 1000
    listener:
      concurrency: 6
      ack-mode: manual_immediate
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 30

kafka:
  transaction:
    topic: duis-wallet-transaction-dev
    concurrency: 3
  rule-hit:
    topic: duis-safety-rule-hits-dev

rules:
  max-transactions-last-minutes:
    id: MAX_TRANSACTIONS_LAST_MINUTES
    minutes: 1
    max-transactions: 2

  max-amount-last-minutes:
    id: MAX_TRANSACTIONS_LAST_MINUTES
    minutes: 5
    max-amount: 1000000000

data:
  redis:
    host: localhost
    port: 6379
    password: Thai@11052004
    timeout: 60000
    database: 1

cache:
  type: redis


