server:
  port: 8081

spring:
  config:
    import: "classpath:common.yml"
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service
    username: root
    password: Thai@11052004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9094
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: all
        retries: 30
        compress-type: lz4
        properties:
          enable-idempotence: true
          max.in.flight.request.per.connect: 5
          spring.json.add.type.header: false


jwt:
  accessTokenSecret: sqWbT3cxuKh1Qg2zWc3RSdvLN0PAZE8mpNqpTxGTxw0=
  refreshTokenSecret: RpHz5z6LHjsAjGfX1txgCO9D/PmNlZJMRRKbM925joU=
  mailSecret: RpHz5z6LHjsAjGfX1txgCO9D/1105ZJMRRKbM925joU=
  accessTokenExpiration: 30000000
  refreshTokenExpiration: 2592000000
  mailExpiration: 300000


#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, metrics, loggers,cache
#  endpoint:
#    health:
#      show-details: always



