server:
  port: 8086

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user-profile
    username: admin
    password: Thai@13082020
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      fileService:
        sliding-window-type: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50

  timelimiter:
    instances:
      userService:
        timeout-duration: 2s
        cancel-running-future: true

  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - feign.RetryableException
          - java.net.SocketTimeoutException

  bulkhead:
    instances:
      userService:
        max-concurrent-calls: 20
        max-wait-duration: 0ms