# prometheus.yaml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'discovery-service'
    eureka_sd_configs:
      - server: 'http://192.168.64.1:8761/'
    metrics_path: '/actuator/prometheus'

    relabel_configs:
      # Chỉ giữ lại những service có cổng 8080–9000
      - source_labels: [ __meta_eureka_app_instance_port ]
        regex: '8[0-9]{3}'
        action: keep
      # Đặt nhãn application cho dễ đọc trong Grafana
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      # (Tùy chọn) đặt nhãn môi trường
      - target_label: environment
        replacement: 'dev'